name: AI Updater Workflow

on:
  push:
    branches:
      - workflow/update-protos
  workflow_dispatch:

jobs:
  call-ai-updater:
    uses: viamrobotics/viam-ai-updater/.github/workflows/ai-updater.yml@main
    with:
        target_branch: workflow/update-protos
        sdk: cpp
    secrets:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
